### ISSUE TITLE
No coverage for ES6 classes which use `extends`

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs-coverage#2]
ES6 classes with the `extends` keyword:

```
class Sub extends Sup {
    constructor( name ) {
        super();
    }
}
```

Causes errors:

```
error: [middleware-jobs]  Error: Line 17: Unexpected reserved word
    at createError (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2015:21)
    at unexpectedTokenError (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2083:13)
    at throwUnexpectedToken (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2088:15)
    at parsePrimaryExpression (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2546:13)
    at parseLeftHandSideExpressionAllowCall (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2639:61)
    at parsePostfixExpression (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2687:16)
    at parseUnaryExpression (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2743:20)
    at parseBinaryExpression (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2832:16)
    at parseConditionalExpression (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:2888:16)
    at parseAssignmentExpression (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:3004:16)
    at parseExpression (/home/pjasiun/workspace/ckeditor5/ckeditor5/node_modules/benderjs-coverage/node_modules/istanbul/node_modules/esprima/esprima.js:3038:16)
error: Test error: Error: Script error for: document/lineardata/openingtag
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://tests.ckeditor.dev:1030/jobs/q1eBf8aZq3ima5Eo/apps/ckeditor/node_modules/requirejs/require.js:166:17)
    at HTMLScriptElement.context.onScriptError (http://tests.ckeditor.dev:1030/jobs/q1eBf8aZq3ima5Eo/apps/ckeditor/node_modules/requirejs/require.js:1701:36)
```

And no coverage for these files.

**Comment by scofalik** [comment]
Fixed with https://github.com/benderjs/benderjs-coverage/commit/7c71d8d5852be4fa8381df20744cc30134da87d1 . Escodegen reports that "Super" is an unsupported node, but everything seems to work fine. Take care and report errors :).
